### ISSUE TITLE
Syntax: case expr

### ISSUE THREAD

**Issue by paulzfm** [paulzfm/LustreAST#1]
The case expr should be like this in Lustre:

```
case var1 of
| true : 1
| false : 0
```

The corresponding AST is like:

```
switch_expr((int),(()),ID(var1,bool,()),case(BOOL(true),INT(1)),case(BOOL(false),INT(0)))
```

The syntax of AST should be 

```
switch_expr(<type>, <clock>, <expr>, <caseStmt> [,<caseStmt>]*)
```

Thus, the `<expr>` is needed.

**Comment by darke1891** [comment]
Fix it in 44c5174a5e53a7a355c6445e428eb7183d2584f2.
